steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-south1-docker.pkg.dev/apac-01072016/invoice-intel/invoice-intel:latest',
      '-f', 'Dockerfile',
      '.'
    ]
images:
  - 'asia-south1-docker.pkg.dev/apac-01072016/invoice-intel/invoice-intel:latest'
